# Generated by Django 5.2.4 on 2025-07-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_notification_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(
                default="test",
                help_text="Enter a brief summary of the book",
                max_length=1000,
            ),
            preserve_default=False,
        ),
    ]
